apiVersion: v1
kind: ConfigMap
metadata:
  name: preset-ecnet-config
  namespace: {{ include "ecnet.namespace" . }}
data:
  preset-ecnet-config.json: |
    {
      "dns": {
        "namespace": {{.Values.ecnet.dns.namespace | mustToJson}},
        "name": {{.Values.ecnet.dns.name | mustToJson}},
        "port": {{.Values.ecnet.dns.port | mustToJson}},
        "protocol": {{.Values.ecnet.dns.protocol | mustToJson}}
      },
      "sidecar": {
        "logLevel": {{.Values.ecnet.proxyLogLevel | mustToJson}},
        "configResyncInterval": {{.Values.ecnet.configResyncInterval | mustToJson}},
        "proxyServerPort": {{.Values.ecnet.proxyServerPort | mustToJson}}
      },
      "repoServer": {
        "ipaddr": {{.Values.ecnet.repoServer.ipaddr | mustToJson}},
        "codebase": {{.Values.ecnet.repoServer.codebase | mustToJson}}
      },
      "pluginChains": {{.Values.ecnet.pluginChains | mustToJson }}
    }
